### ISSUE TITLE
TypeError: Input graph is not a networkx graph type during test

### ISSUE THREAD

**Issue by dynaryu** [pgmpy/pgmpy#1147] opened 2019-08-07 10:57 UTC
Two errors occurred during test as below:

======================================================================
ERROR: test_get_init_values (pgmpy.tests.test_estimators.test_SEMEstimator.TestSEMEstimator)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/hyeuk/miniconda3/envs/pgmpy/lib/python3.6/site-packages/networkx/convert.py", line 46, in _prep_create_using
    create_using.clear()
TypeError: clear() missing 1 required positional argument: 'self'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hyeuk/Projects/pgmpy/pgmpy/tests/test_estimators/test_SEMEstimator.py", line 81, in test_get_init_values
    data=self.demo_data, method=method
  File "/home/hyeuk/Projects/pgmpy/pgmpy/estimators/SEMEstimator.py", line 161, in get_init_values
    scaling_vars = self.model.to_SEMGraph().get_scaling_indicators()
  File "/home/hyeuk/Projects/pgmpy/pgmpy/models/SEM.py", line 925, in to_SEMGraph
    nx.from_numpy_matrix(self.B.T, create_using=nx.DiGraph),
  File "/home/hyeuk/miniconda3/envs/pgmpy/lib/python3.6/site-packages/networkx/convert_matrix.py", line 549, in from_numpy_matrix
    G = _prep_create_using(create_using)
  File "/home/hyeuk/miniconda3/envs/pgmpy/lib/python3.6/site-packages/networkx/convert.py", line 48, in _prep_create_using
    raise TypeError("Input graph is not a networkx graph type")
TypeError: Input graph is not a networkx graph type

======================================================================
ERROR: test_to_from_lisrel (pgmpy.tests.test_models.test_SEM.TestSEMGraph)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/hyeuk/miniconda3/envs/pgmpy/lib/python3.6/site-packages/networkx/convert.py", line 46, in _prep_create_using
    create_using.clear()
TypeError: clear() missing 1 required positional argument: 'self'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hyeuk/Projects/pgmpy/pgmpy/tests/test_models/test_SEM.py", line 1240, in test_to_from_lisrel
    demo_graph = demo_lisrel.to_SEMGraph()
  File "/home/hyeuk/Projects/pgmpy/pgmpy/models/SEM.py", line 925, in to_SEMGraph
    nx.from_numpy_matrix(self.B.T, create_using=nx.DiGraph),
  File "/home/hyeuk/miniconda3/envs/pgmpy/lib/python3.6/site-packages/networkx/convert_matrix.py", line 549, in from_numpy_matrix
    G = _prep_create_using(create_using)
  File "/home/hyeuk/miniconda3/envs/pgmpy/lib/python3.6/site-packages/networkx/convert.py", line 48, in _prep_create_using
    raise TypeError("Input graph is not a networkx graph type")
TypeError: Input graph is not a networkx graph type

### Your environment
ubuntu 18.04.1
(pgmpy) $ conda list
_libgcc_mutex             0.1                        main  
blas                      1.0                         mkl  
ca-certificates           2019.5.15                     0  
certifi                   2019.6.16                py36_1  
cffi                      1.12.3           py36h2e261b9_0  
cudatoolkit               10.0.130                      0  
cudnn                     7.6.0                cuda10.0_0  
decorator                 4.4.0                    py36_1  
intel-openmp              2019.4                      243  
joblib                    0.13.2                   py36_0  
libedit                   3.1.20181209         hc058e9b_0  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
mkl                       2019.4                      243  
mkl_fft                   1.0.12           py36ha843d7b_0  
mkl_random                1.0.2            py36hd81dba3_0  
mock                      3.0.5                    py36_0  
ncurses                   6.1                  he6710b0_1  
networkx                  2.1                      py36_0  
ninja                     1.9.0            py36hfd86e86_0  
numpy                     1.16.4           py36h7e9f1db_0  
numpy-base                1.16.4           py36hde5b4d6_0  
openssl                   1.1.1c               h7b6447c_1  
pandas                    0.23.4           py36h04863e7_0  
patsy                     0.5.1                    py36_0  
pgmpy                     0.1.8.dev34              pypi_0    pypi
pip                       19.1.1                   py36_0  
pycparser                 2.19                     py36_0  
pyparsing                 2.4.0                      py_0  
python                    3.6.9                h265db76_0  
python-dateutil           2.8.0                    py36_0  
pytorch                   1.0.1           cuda100py36he554f03_0  
pytz                      2019.1                     py_0  
readline                  7.0                  h7b6447c_5  
scipy                     1.2.1            py36h7c811a0_0  
setuptools                41.0.1                   py36_0  
six                       1.12.0                   py36_0  
sqlite                    3.29.0               h7b6447c_0  
statsmodels               0.9.0            py36h035aef0_0  
tk                        8.6.8                hbc83047_0  
tqdm                      4.32.1                     py_0  
wheel                     0.33.4                   py36_0  
xz                        5.2.4                h14c3975_4  
zlib                      1.2.11               h7b6447c_3  

### Steps to reproduce
python -m unittest -v

**Comment by ankurankan** [comment] 2019-09-05 11:19
@dynaryu I am not sure why this failing for you. I checked most of the dependencies and they are the same for me and it works on my machine.

**Comment by ankurankan** [comment] 2020-02-12 12:42
Closing because not able to reproduce

**Closed as completed by ankurankan** 2020-02-12 12:42 UTC
