### ISSUE TITLE
Confusing error in fit(): IndexError index 0 is out of bounds

### ISSUE THREAD

**Issue by kmbnw** [pgmpy/pgmpy#538] opened 2015-12-13 01:07 UTC
EDIT: I am using the book/v0.1 branch.

My apologies if this is in the bug list somewhere; I looked through the active bugs and searched, but I couldn't find a duplicate.

I'm experimenting with the examples from the book "Mastering Probabilistic Graphical Models in Python".  In setting up what seemed like some fairly simple models, I discovered what looks like a bug (occurs on both Python 2.7 and Python 3.4, on Ubuntu 14.04 LTS).  

I could be specifying the models wrong, but the error is not informative enough for me to tell what might be happening.

The following code works:

``` python
data = np.random.randint(low=0, high=2, size=(1000, 3))
data = pd.DataFrame(data, columns=[
    'cost',
    'quality', 
    'location'
    ])
train = data[:750]
restaurant_model = BayesianModel([
        ('location', 'cost')
    ])
restaurant_model.check_model()
restaurant_model.fit(train)
```

But when I remove the unused 'quality' column, I get an error:

``` python
data = np.random.randint(low=0, high=2, size=(1000, 2))
data = pd.DataFrame(data, columns=[
    'cost',
   # 'quality', 
    'location'
    ])
train = data[:750]
restaurant_model = BayesianModel([
        ('location', 'cost')
    ])
restaurant_model.check_model()
restaurant_model.fit(train)

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-31-fb9099559416> in <module>()
      6     ])
      7 restaurant_model.check_model()
----> 8 restaurant_model.fit(train)

/home/krystab/virtualenvs/compmodel3/lib/python3.4/site-packages/pgmpy-0.1.0-py3.4.egg/pgmpy/models/BayesianModel.py in fit(self, data, estimator_type)
    555         estimator = estimator_type(self, data)
    556 
--> 557         cpds_list = estimator.get_parameters()
    558         self.add_cpds(*cpds_list)
    559 

/home/krystab/virtualenvs/compmodel3/lib/python3.4/site-packages/pgmpy-0.1.0-py3.4.egg/pgmpy/estimators/MLE.py in get_parameters(self)
     70                 var_card = self.node_card[node]
     71                 state_counts = self.data.groupby([node] + self.model.predecessors(node)).count()
---> 72                 values = state_counts.iloc[:, 0].reshape(var_card,
     73                                                          np.product(parent_card))
     74                 cpd = TabularCPD(node, var_card, values,

/home/krystab/virtualenvs/compmodel3/lib/python3.4/site-packages/pandas/core/indexing.py in __getitem__(self, key)
   1185     def __getitem__(self, key):
   1186         if type(key) is tuple:
-> 1187             return self._getitem_tuple(key)
   1188         else:
   1189             return self._getitem_axis(key, axis=0)

/home/krystab/virtualenvs/compmodel3/lib/python3.4/site-packages/pandas/core/indexing.py in _getitem_tuple(self, tup)
   1424                 continue
   1425 
-> 1426             retval = getattr(retval, self.name)._getitem_axis(key, axis=axis)
   1427 
   1428             # if the dim was reduced, then pass a lower-dim the next time

/home/krystab/virtualenvs/compmodel3/lib/python3.4/site-packages/pandas/core/indexing.py in _getitem_axis(self, key, axis)
   1478                 self._is_valid_integer(key, axis)
   1479 
-> 1480             return self._get_loc(key, axis=axis)
   1481 
   1482     def _convert_to_indexer(self, obj, axis=0, is_setter=False):

/home/krystab/virtualenvs/compmodel3/lib/python3.4/site-packages/pandas/core/indexing.py in _get_loc(self, key, axis)
     87 
     88     def _get_loc(self, key, axis=0):
---> 89         return self.obj._ixs(key, axis=axis)
     90 
     91     def _slice(self, obj, axis=0, kind=None):

/home/krystab/virtualenvs/compmodel3/lib/python3.4/site-packages/pandas/core/frame.py in _ixs(self, i, axis)
   1741             """
   1742 
-> 1743             label = self.columns[i]
   1744             if isinstance(i, slice):
   1745                 # need to return view

/home/krystab/virtualenvs/compmodel3/lib/python3.4/site-packages/pandas/core/index.py in __getitem__(self, key)
   1074 
   1075         if np.isscalar(key):
-> 1076             return getitem(key)
   1077 
   1078         if isinstance(key, slice):

IndexError: index 0 is out of bounds for axis 0 with size 0
```

I get the same error if I specify the model as (and adding only the quality column back into the dataframe):

``` python
restaurant_model = BayesianModel([
        ('location', 'cost'),
        ('quality', 'cost'),
    ])
```

In case it helps, this is the output of 'pip freeze' for my Python 3 virtualenv:

```
 pip freeze
Jinja2==2.8
MarkupSafe==0.23
Pygments==2.0.2
backports-abc==0.4
coverage==4.0.3
coveralls==1.1
decorator==4.0.6
docopt==0.6.2
ipykernel==4.2.1
ipython==4.0.1
ipython-genutils==0.1.0
ipywidgets==4.1.1
jsonschema==2.5.1
jupyter==1.0.0
jupyter-client==4.1.1
jupyter-console==4.0.3
jupyter-core==4.0.6
mistune==0.7.1
mock==1.3.0
nbconvert==4.1.0
nbformat==4.0.1
networkx==1.9.1
nose==1.3.7
notebook==4.0.6
numpy==1.9.2
pandas==0.16.2
path.py==8.1.2
pbr==1.8.1
pexpect==4.0.1
pgmpy==0.1.0
pickleshare==0.5
ptyprocess==0.5
pyparsing==2.0.3
python-dateutil==2.4.2
pytz==2015.7
pyzmq==15.1.0
qtconsole==4.1.1
requests==2.8.1
scipy==0.16.0
simplegeneric==0.8.1
six==1.10.0
terminado==0.5
tornado==4.3
traitlets==4.0.0
```

**Comment by khalibartan** [comment] 2015-12-13 05:44
@kmbnw  can you give me the complete code, I'll run it on dev branch and If error reproduce I'll try to fix the bug. Also you should not use a stale branch , it hasn't been updated since a long time .

**Comment by khalibartan** [comment] 2015-12-13 05:51
@kmbnw Same error is being caused even in `dev` branch. Will look into the matter .
But it is also deprecated that you should not use a stale branch for working, it hasn't been updated since a long time .
Ping @ankurankan 
Is this a known issue ?

**Comment by kmbnw** [comment] 2015-12-13 06:01
Ok.  I will try with the dev branch.  Is master also stale?  Do you still want the rest of the code?

**Comment by khalibartan** [comment] 2015-12-13 10:09
@kmbnw  you don't need to reproduce the code, I have mentioned that same error is being caused in dev, and yes master is also a stale branch .

**Comment by khalibartan** [comment] 2015-12-13 18:07
@kmbnw There is no need for the rest of code. Also same error is being caused in the dev , we will look into the issue.

**Comment by kmbnw** [comment] 2015-12-13 19:57
Please note that changing this to floating point numbers causes it to fail even with the 'extra' column that makes it work with integers:

``` python
data = np.random.uniform(0, 2, size=(1000,4))
data = pd.DataFrame(data, columns=[
    'cost',
    'quality', 
    'location', 
    'no_of_people'
    ])
train = data[:750]
test = data[750:].drop('cost', axis=1)

restaurant_model = BayesianModel([
        ('location', 'cost'),
        ('quality', 'cost')
    ])
restaurant_model.check_model()
restaurant_model.fit(train)

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-26-39a49b4b2ddf> in <module>()
      6     ])
      7 restaurant_model.check_model()
----> 8 restaurant_model.fit(train)

/home/krystab/virtualenvs/compmodel3/lib/python3.4/site-packages/pgmpy-0.1.0-py3.4.egg/pgmpy/models/BayesianModel.py in fit(self, data, estimator_type)
    555         estimator = estimator_type(self, data)
    556 
--> 557         cpds_list = estimator.get_parameters()
    558         self.add_cpds(*cpds_list)
    559 

/home/krystab/virtualenvs/compmodel3/lib/python3.4/site-packages/pgmpy-0.1.0-py3.4.egg/pgmpy/estimators/MLE.py in get_parameters(self)
     71                 state_counts = self.data.groupby([node] + self.model.predecessors(node)).count()
     72                 values = state_counts.iloc[:, 0].reshape(var_card,
---> 73                                                          np.product(parent_card))
     74                 cpd = TabularCPD(node, var_card, values,
     75                                  evidence=parents,

/home/krystab/virtualenvs/compmodel3/lib/python3.4/site-packages/pandas/core/series.py in reshape(self, *args, **kwargs)
    785             return self
    786 
--> 787         return self.values.reshape(shape, **kwargs)
    788 
    789     iget_value = _ixs

ValueError: total size of new array must be unchanged
```

Which looks like the same error in https://github.com/pgmpy/pgmpy/issues/501

**Comment by yashu-seth** [comment] 2015-12-13 20:01
@kmbnw I have located the cause of the bug. We will fix it as soon as possible.
#541

**Comment by ankurankan** [comment] 2015-12-17 04:58
@kmbnw This is fixed now. Please pull the latest changes. Also failing in the case of `float` is an expected behavior since we currently just support discrete variables.

**Closed as completed by ankurankan** 2015-12-17 04:58 UTC
