### ISSUE TITLE
NotImplementedError: 'All the args are expected to ', 'be instances of the same factor class.'

### ISSUE THREAD

**Issue by AlexGoico** [pgmpy/pgmpy#889] opened 2017-07-28 20:07 UTC
I have the following error:
```
Traceback (most recent call last):
  File "/home/agoico/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-55-8f819a15a016>", line 1, in <module>
    BeliefPropagation(model)
  File "/home/agoico/anaconda3/lib/python3.6/site-packages/pgmpy-0.1.3-py3.6.egg/pgmpy/inference/ExactInference.py", line 323, in __init__
    self.junction_tree = model.to_junction_tree()
  File "/home/agoico/anaconda3/lib/python3.6/site-packages/pgmpy-0.1.3-py3.6.egg/pgmpy/models/BayesianModel.py", line 643, in to_junction_tree
    return mm.to_junction_tree()
  File "/home/agoico/anaconda3/lib/python3.6/site-packages/pgmpy-0.1.3-py3.6.egg/pgmpy/models/MarkovModel.py", line 520, in to_junction_tree
    clique_potential *= factor_product(*clique_factors)
  File "/home/agoico/anaconda3/lib/python3.6/site-packages/pgmpy-0.1.3-py3.6.egg/pgmpy/factors/base.py", line 66, in factor_product
    "be instances of the same factor class.")
NotImplementedError: ('All the args are expected to ', 'be instances of the same factor class.')
```
for the following model:
```
network unknown {
}
variable A {
  type discrete [ 2 ] { no, yes };
}
variable B {
  type discrete [ 2 ] { no, yes };
}
variable C {
  type discrete [ 2 ] { no, yes };
}
variable D {
  type discrete [ 2 ] { no, yes };
}
variable E {
  type discrete [ 2 ] { no, yes };
}
variable F {
  type discrete [ 2 ] { no, yes };
}
variable G {
  type discrete [ 2 ] { no, yes };
}
variable H {
  type discrete [ 2 ] { no, yes };
}
variable I {
  type discrete [ 2 ] { no, yes };
}
variable J {
  type discrete [ 2 ] { no, yes };
}
variable K {
  type discrete [ 2 ] { no, yes };
}
variable L {
  type discrete [ 2 ] { no, yes };
}
variable M {
  type discrete [ 2 ] { yes, no };
}
probability ( A ) {
  table 0.11, 0.89;
}
probability ( B ) {
  table 0.09, 0.91;
}
probability ( C | A ) {
  (yes) 0.08, 0.92;
  (no) 0.1, 0.9;
}
probability ( D | B ) {
  (yes) 0.07, 0.93;
  (no) 0.9, 0.1;
}
probability ( E ) {
  table 0.2, 0.801; 
}
probability ( F | A, K ) {
  (yes, yes) 0.11, 0.89;
  (yes, no) 0.78, 0.22;
  (no, yes) 0.8, 0.2;
  (no, no) 0.85, 0.15;
}
probability ( G | A ) {
  (yes) 0.04, 0.96;
  (no) 0.83, 0.17;
}
probability ( H | F, G ) {
  (yes, yes) 0.08, 0.92;
  (yes, no) 0.1, 0.9;
  (no, yes) 0.11, 0.89;
  (no, no) 0.88, 0.12;
}
probability ( I | C, D ) {
  (yes, yes) 0.05, 0.95;
  (yes, no) 0.49, 0.51;
  (no, yes) 0.52, 0.48;
  (no, no) 0.89, 0.11;
}
probability ( J | I, K ) {
  (yes, yes) 0.09, 0.91;
  (yes, no) 0.92, 0.08;
  (no, yes) 0.52, 0.48;
  (no, no) 0.9, 0.1;
}
probability ( K | E ) {
  (yes) 0.09, 0.91;
  (no) 0.89, 0.11;
}
probability ( L | H ) {
  (yes) 0.05, 0.95;
  (no) 0.9, 0.1;
}
probability ( M | J, L ) {
  (yes, yes) 0.05, 0.95;
  (yes, no) 0.49, 0.51;
  (no, yes) 0.89, 0.11;
  (no, no) 0.91, 0.09;
}
```
Any advice on why this is not working with pgmpy would be very helpful.

**Comment by khalibartan** [comment] 2017-07-29 02:44
@AlexGoico Could you share the code snippet of what you were trying to do?

**Comment by AlexGoico** [comment] 2017-07-29 04:14
Yes, sorry I failed to mention the code snippet:
```python
from pgmpy.inference.ExactInference import BeliefPropagation
from pgmpy.readwrite.BIF import BIFReader
model = BIFReader(path="model.bif").get_model()
bp = BeliefPropagation(model)
```

**Comment by khalibartan** [comment] 2017-07-29 04:36
@AlexGoico It is running fine on my system. Here is the output of a query
```
In [24]: results = bp.query(variables=['A','B'], evidence={'C':0, 'D': 0})

In [25]: print(results['A'])
╒═════╤══════════╕
│ A   │   phi(A) │
╞═════╪══════════╡
│ A_0 │   0.0900 │
├─────┼──────────┤
│ A_1 │   0.9100 │
╘═════╧══════════╛

In [26]: print(results['B'])
╒═════╤══════════╕
│ B   │   phi(B) │
╞═════╪══════════╡
│ B_0 │   0.0076 │
├─────┼──────────┤
│ B_1 │   0.9924 │
╘═════╧══════════╛
```
Did you install pgmpy using pip install ? pip version of pgmpy is old, Please use latest version of pgmpy by downloading the source from git repository and the following the install instructions mentioned in README

**Comment by AlexGoico** [comment] 2017-07-29 06:25
I am using a recent version of pgmpy and am still unable to get past the previous error. Running `pip show pgmpy` I get
```
Name: pgmpy
Version: 0.1.3
Summary: A library for Probabilistic Graphical Models
Home-page: https://github.com/pgmpy/pgmpy
Author: People
Author-email: None
License: None
Location: /home/typedeph/anaconda3/lib/python3.6/site-packages/pgmpy-0.1.3-py3.6.egg
Requires: networkx, scipy, numpy
```

**Comment by khalibartan** [comment] 2017-07-29 16:55
@AlexGoico Yeah my mistake, on current dev it is giving the error. Mine env was using same version of pgmpy but not the latest.

**Comment by khalibartan** [comment] 2017-08-08 06:37
@ankurankan Error is quite weired. I tried running the code samples 3-4 times and sometimes it ran fine but on some occasions it gave me an error because we are calling factor_product on a empty list of factors at this [line](https://github.com/pgmpy/pgmpy/blob/dev/pgmpy/models/MarkovModel.py#L520). I haven't studied markov models can you try to fix it?

@AlexGoico Can you also verify this by running the code sample in your ipython console once and closing it and running it again.

**Comment by khalibartan** [comment] 2017-08-08 06:38
Adding label Base Model because bug is in construction of Junction tree.

**Comment by jonadsimon** [comment] 2017-11-03 15:59
I am encountering this same error when trying to do a basic inference with evidence.

It's an extremely simple model:


```
import pandas as pd
from pgmpy.models import BayesianModel

data = pd.read_csv('data/queue_state_transitions_reshaped.csv')
model = BayesianModel([('prev_state','new_state')])
model.fit(data.iloc[:,:2])
```

Evidence-free inference works:

```
infer.query(['new_state'])

# {'new_state': <DiscreteFactor representing phi(new_state:10) at 0x119b39ad0>}
```

But if I include any evidence, I get an error. For example, this query:

```
infer.query(['next_state'], evidence={'prev_state': 8})


---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-84-4c60502fe152> in <module>()
      9 
     10 # print(infer.query(['next_state'], evidence={'prev_state': 8}) ['next_state'])
---> 11 infer.query(['next_state'], evidence={'prev_state': 8})
     12 # infer.query(['new_state'])
     13 

/Users/jonathansimon/.pyenv/versions/2.7.10/lib/python2.7/site-packages/pgmpy/inference/ExactInference.pyc in query(self, variables, evidence, elimination_order)
    125         """
    126         return self._variable_elimination(variables, 'marginalize',
--> 127                                           evidence=evidence, elimination_order=elimination_order)
    128 
    129     def max_marginal(self, variables=None, evidence=None, elimination_order=None):

/Users/jonathansimon/.pyenv/versions/2.7.10/lib/python2.7/site-packages/pgmpy/utils/state_name.pyc in __call__(self, f, instance, args, kwargs)
    165 
    166         if not method_self.state_names:
--> 167             return f(*args, **kwargs)
    168         else:
    169             self.state_names = method_self.state_names

/Users/jonathansimon/.pyenv/versions/2.7.10/lib/python2.7/site-packages/pgmpy/inference/ExactInference.pyc in _variable_elimination(self, variables, operation, evidence, elimination_order)
     92         query_var_factor = {}
     93         for query_var in variables:
---> 94             phi = factor_product(*final_distribution)
     95             query_var_factor[query_var] = phi.marginalize(list(set(variables) -
     96                                                                set([query_var])),

/Users/jonathansimon/.pyenv/versions/2.7.10/lib/python2.7/site-packages/pgmpy/factors/base.pyc in factor_product(*args)
     64     elif len(set(map(type, args))) != 1:
     65             raise NotImplementedError("All the args are expected to ",
---> 66                                       "be instances of the same factor class.")
     67 
     68     return reduce(lambda phi1, phi2: phi1 * phi2, args)

NotImplementedError: ('All the args are expected to ', 'be instances of the same factor class.')
```

I am using the latest version of pgmpy which I cloned from the github repo [here](https://github.com/pgmpy/pgmpy)

**Comment by ankurankan** [comment] 2017-11-05 00:01
@StarvingMathematician I think the error is because there's a typo in your code. In the query method you have used `next_state` instead of `new_state`. I tried running the code on random data using `new_state` and it works fine.

**Closed as completed** 2017-11-05 09:05 UTC
Labels: Bug, Model

**Comment by hnoren** [comment] 2019-06-19 09:50
I am encountering this error when I have a large number of evidence variables listed in the query.  I am using the most updated version of pgmpy.  Is this error related to the version of python being used or the version of any of pgmpy's dependencies?


`probability = bn_model_infer.query(['atHarmony_0', 'noop_atHarmony_0', 'moveHC_0', 'moveHD_0', 'atHarmony_1', 'noop_atHarmony_1', 'atColumbus_1', 'noop_atColumbus_1', 'atDestiny_1', 'noop_atDestiny_1', 'moveHC_1', 'moveHD_1', 'moveCU_1', 'moveDU_1', 'atHarmony_2', 'atColumbus_2', 'atDestiny_2', 'atUnity_2', 'moveHCxmoveHD_0', 'moveABxmoveAD_1', 'moveABxmoveAD_1', 'moveABxmoveBC_1', 'moveABxmoveDC_1', 'moveABxloadD_1', 'moveADxmoveBC_1', 'moveADxmoveDC_1', 'moveADxloadD_1', 'moveBCxmoveDC_1', 'moveBCxloadD_1', 'moveDCxloadD_1', 'obs_moveHC_0', 'obs_moveHD_0', 'obs_MoveHC_1', 'obs_MoveHD_1', 'obs_MoveCU_1', 'obs_MoveDU_1'], {'atHarmony_0':1, 'moveHCxmoveHD_0':1, 'moveABxmoveAD_1':1, 'moveABxmoveAD_1':1, 'moveABxmoveBC_1':1, 'moveABxmoveDC_1':1, 'moveABxloadD_1':1, 'moveADxmoveBC_1':1, 'moveADxmoveDC_1':1, 'moveADxloadD_1':1, 'moveBCxmoveDC_1':1, 'moveBCxloadD_1':1, 'moveDCxloadD_1':1, 'obs_moveHD_0':1, 'obs_MoveDU_1':1, 'atHarmony_0':1, 'moveHCxmoveHD_0':1, 'moveABxmoveAD_1':1, 'moveABxmoveAD_1':1, 'moveABxmoveBC_1':1, 'moveABxmoveDC_1':1, 'moveABxloadD_1':1, 'moveADxmoveBC_1':1, 'moveADxmoveDC_1':1, 'moveADxloadD_1':1, 'moveBCxmoveDC_1':1, 'moveBCxloadD_1':1, 'moveDCxloadD_1':1, 'obs_moveHD_0':1, 'obs_MoveDU_1':1})`

gives error: `NotImplementedError: ('All the args are expected to ', 'be instances of the same factor class.')`

`pip freeze
decorator==4.4.0
networkx==1.11
numpy==1.16.4
pandas==0.24.2
patsy==0.5.1
pgmpy==0.1.7
pyparsing==2.4.0
python-dateutil==2.8.0
pytz==2019.1
scipy==1.3.0
six==1.12.0
statsmodels==0.9.0
torch==1.1.0
tqdm==4.32.2
wrapt==1.11.2
`

**Comment by ankurankan** [comment] 2019-06-20 14:12
@hnoren I am not sure why this is happening. Could you share your code, so that I can reproduce this issue? Also, if you are using the latest pgmpy, it might be happening because of `networkx==1.11`. You can also try upgrading networkx and pgmpy to the latest dev.

**Comment by fborcic** [comment] 2020-01-19 20:56
In my case, the error meant that I was trying to get the distribution for a variable appearing in the evidence dict. Judging by the description, I'd say OP might have had the same problem

**Comment by ankurankan** [comment] 2020-01-20 16:02
@fborcic I have recently added a more meaningful message in the case when any of the variables appear both in `variables` and `evidence`.
