### ISSUE TITLE
Making IndependenceAssertion Hashable

### ISSUE THREAD

**Issue by aelnouby** [pgmpy/pgmpy#638] opened 2016-02-18 18:47 UTC
Hi all,

I am a newbie here , I was going through the TODOs in #548 , i started investigating the first issue
 independencies/Independencies.py: # TODO: write reduce function.

I think making the IndependenceAssertion hashable would be a good idea , it will solve this issue by storing the objects in a set eliminating any duplication from the beginning , also making it hashable can be useful in the future 

Please tell me what you think , and if this might cause any problems.

**Comment by khalibartan** [comment] 2016-02-19 02:02
@aelnouby Yeah you are right. But there is a PR that deals with this issue and issue #531

**Comment by chrisittner** [comment] 2016-02-19 03:19
Now there are two :D (Also, this issue is duplicate of #531 )

**Comment by khalibartan** [comment] 2016-02-22 15:49
@ankurankan Fixed. Can be closed now and #531 too.

**Closed as completed** 2016-02-23 03:08 UTC
