### ISSUE TITLE
The result of each DAG (pattern) construction is different

### ISSUE THREAD

**Issue by OccZa** [pgmpy/pgmpy#1510] opened 2022-03-23 06:24 UTC
### Subject of the issue
I use est.skeleton_to_pdag and est.pdag_to_dag to generate different dictionaries every time, so the final generated bayes network is also different. I want to know what is the reason for this. Can I fix my results through random seed? 
In the file plus contains the two result pictures I generated: result A and result B.

Thanks！
### Your environment
* pgmpy version 0.1.11
* Python version 3.8
* Operating System Windows

### Steps to reproduce
Tell us how to reproduce this issue. Please provide a **minimal reproducible code** of
the issue you are facing if possible.

### Expected behaviour
I wonder if this module can set random seeds to fix the result.

**Comment by OccZa** [comment] 2022-03-23 06:24
![resultA](https://user-images.githubusercontent.com/82425726/159636530-726d799d-4a8e-4c77-8544-e6f967d0cc82.png)
![resultB](https://user-images.githubusercontent.com/82425726/159636548-60b1b6e7-276c-4dfa-8c3c-ce6168e97c2d.png)

**Comment by ankurankan** [comment] 2022-03-30 00:18
@OccZa I am not able to reproduce this issue. From my understanding, if you are using the stable version of the PC algorithm, it should return the same DAG every time. I tried to test it using simulated data and it seems to be returning the same DAG in each run:
```python
In [17]: from pgmpy.utils import get_example_model
In [18]: from pgmpy.estimators import PC
In [19]: model = get_example_model('alarm')

In [20]: data = model.simulate(int(1e3))
Generating for node: BP: 100%|██████████████████████████████████████████| 37/37 [00:00<00:00, 184.14it/s]

In [21]: dag_edges = []

In [22]: for i in range(5):
    ...:     dag_edges.append(set(PC(data).estimate().edges()))
    ...: 
Working for n conditional variables: 5: 100%|██████████████████████████████| 5/5 [00:34<00:00,  6.86s/it]
Working for n conditional variables: 5: 100%|██████████████████████████████| 5/5 [00:20<00:00,  4.13s/it]
Working for n conditional variables: 5: 100%|██████████████████████████████| 5/5 [00:17<00:00,  3.47s/it]
Working for n conditional variables: 5: 100%|██████████████████████████████| 5/5 [00:17<00:00,  3.43s/it]
Working for n conditional variables: 5: 100%|██████████████████████████████| 5/5 [00:17<00:00,  3.43s/it]

In [23]: for i in range(1, 5):
    ...:     assert (dag_edges[0] == dag_edges[i])
    ...: 

```
Would it be possible to share your code and data so that I can reproduce this?

**Comment by ankurankan** [comment] 2022-06-30 07:06
@OccZa I think I have finally found the problem. It should be fixed with: https://github.com/pgmpy/pgmpy/pull/1537

**Closed as completed by ankurankan** 2022-06-30 07:06 UTC
