### ISSUE TITLE
TypeError: 'dict_keyiterator' object is not subscriptable

### ISSUE THREAD

**Issue by CurtisRose** [pgmpy/pgmpy#1179] opened 2019-11-03 18:42 UTC
### Subject of the issue
(base) C:\Users\TsNRe\School\Artificial_Intelligence>python dbn.py
[('D', 0), ('G', 0), ('D', 1), ('G', 1), ('I', 0), ('I', 1)]
[(('D', 0), 2), (('G', 0), 2), (('D', 1), 2), (('G', 1), 2), (('I', 0), 2), (('I', 1), 2)]
Traceback (most recent call last):
  File "dbn.py", line 42, in <module>
    dbn.initialize_initial_state()
  File "C:\Users\TsNRe\Anaconda3\lib\site-packages\pgmpy\models\DynamicBayesianNetwork.py", line 510, in initialize_initial_state
    if all(x[1] == parents[0][1] for x in parents):
  File "C:\Users\TsNRe\Anaconda3\lib\site-packages\pgmpy\models\DynamicBayesianNetwork.py", line 510, in <genexpr>
    if all(x[1] == parents[0][1] for x in parents):
TypeError: 'dict_keyiterator' object is not subscriptable

### Your environment
* pgmpy version 0.1.7
* Python version 3.7.4
* Operating System Windows 10
Networkx 2.X

### Steps to reproduce
Run this with networkx 2.X

### Expected behaviour
Shouldn't break

### Actual behaviour
(base) C:\Users\TsNRe\School\Artificial_Intelligence>python dbn.py
[('D', 0), ('G', 0), ('D', 1), ('G', 1), ('I', 0), ('I', 1)]
[(('D', 0), 2), (('G', 0), 2), (('D', 1), 2), (('G', 1), 2), (('I', 0), 2), (('I', 1), 2)]
Traceback (most recent call last):
  File "dbn.py", line 42, in <module>
    dbn.initialize_initial_state()
  File "C:\Users\TsNRe\Anaconda3\lib\site-packages\pgmpy\models\DynamicBayesianNetwork.py", line 510, in initialize_initial_state
    if all(x[1] == parents[0][1] for x in parents):
  File "C:\Users\TsNRe\Anaconda3\lib\site-packages\pgmpy\models\DynamicBayesianNetwork.py", line 510, in <genexpr>
    if all(x[1] == parents[0][1] for x in parents):
TypeError: 'dict_keyiterator' object is not subscriptable

You guys had this as an issue and then resolved it?? Why? Because it was a problem with networkx 2.X? Well you say you should have 2.X. So that sounds like a pgmpy problem, not a networkx problem.
If I set networkx back to 1.11 as this guy: https://github.com/pgmpy/pgmpy/issues/927 recommended, it works.

**Comment by ankurankan** [comment] 2019-11-05 17:36
Duplicate of #927

**Closed as completed by ankurankan** 2019-11-05 17:36 UTC
