### ISSUE TITLE
BeliefPropagation yields wrong results on BayesianModel with undirected cycles

### ISSUE THREAD

**Issue by dddpt** [pgmpy/pgmpy#1048] opened 2018-12-12 10:06 UTC
### Environment
* pgmpy 0.1.6
* __networkx 1.11__ (needed for BeliefPropagation to work, see [issue 1034](https://github.com/pgmpy/pgmpy/issues/1034) )
* Python 3.7
* Mac OS 10.14.1

### The Bayesian network

I am using bayesian networks and pgmpy to do inference on someone's genes based on his relative's genes. Here is a drawing of the example network we'll study for this bug:
![2018-12-12 09 59 29](https://user-images.githubusercontent.com/2746311/49858208-a6f93e80-fdf4-11e8-9a30-97f25e04d4bb.jpg)
We want to infer one gene of our target based on the gene of his spouse and all of his children.
See the code at the end of the post for the pgmpy implementation

The takeaways from genes' inheritance for the TabularCPD are:
* a gene can be in three states AA, Aa and aa (numbered 0, 1, 2).
* if both parents' genes are in states AA, the genes of each child is AA with certainty. Same goes if both parents are aa.
* if one parent is AA and one is aa, each child is Aa with certainty.
* if one parent is AA and one is Aa, each child will be AA or Aa with 0.5 probability. (Same if parents are aa and Aa)

### Expected behaviour

We assume that the spouse and all the children are AA.
It follows that the most likely outcome is that the target is AA, he still has a small chance of being Aa but he cannot be aa.
Moreover, as we increase the number of children (and they're all AA), the target's probability to be AA will also increase. (if he is Aa, the probability that all his children are AA is 0.5^nbChildren)

We checked the calculations with matlab, as expected we obtain an increasing AA probability:
Pr(target=AA): 0.7    0.8235    0.9032    0.9492    0.9739
Pr(target=Aa): 0.3    0.1765    0.0968    0.0508    0.0261
Pr(target=aa): 0       0         0         0         0
first column is with 1 child and spouse AA, second with 2 children and spouse AA, third with 3, etc...

### Actual behaviour

With 1 or 2 children, pgmpy yields the correct values. For more than 2 children, it gets stuck to the 2 children probabilities: 
Pr(target=AA): 0.7    0.8235    0.8235    0.8235    0.8235
Pr(target=Aa): 0.3    0.1765    0.1765    0.1765    0.1765
Pr(target=aa): 0       0         0         0         0
Same as before, first column is with 1 child and spouse AA, second with 2 children and spouse AA, third with 3, etc...

### Conclusion

I'd be very happy to learn we actually just missed an intermediary step in our code!

If it's indeed a bug as I think, my guess for the source of the bug would be in the handling of cycles and cliques in either BayesianModel.to_junction_tree() or BeliefPropagation given that the bug first appears in a network with more than 1 undirected cycle. I didn't dive into it yet.

If it's a bug bug affects one of the core functionality of pgmpy and is non-trivial to detect, so I'd say it's quite an important bug to solve. We have been using pgmpy for 2 months before noticing our results were off-mark.

Thanks for reading this loong bug report 'til the end! ;-)

### pgmpy code:

In the code, you can vary the number of children by changing the NB_CHILDREN variable.

```python
from pgmpy.models import BayesianModel
from pgmpy.inference.ExactInference import VariableElimination, BeliefPropagation
from pgmpy.factors.discrete import TabularCPD
import copy



# Family parameters
# =============================================

NB_CHILDREN = 3
edges = [(sp, "child" + str(c)) for c in range(1, NB_CHILDREN + 1) for sp in ["target", "spouse"]]
evidence = {"child" + str(c): 0 for c in range(1, NB_CHILDREN + 1)}
evidence["spouse"] = 0

# Allele distributions & Mendelian inheritance
# =============================================
inheritance_values = [
    [1, 0.5, 0, 0.5, 0.25, 0, 0, 0, 0],
    [0, 0.5, 1, 0.5, 0.5, 0.5, 1, 0.5, 0],
    [0, 0, 0, 0, 0.25, 0.5, 0, 0.5, 1]
]
apriori_values = [[0.49,0.42,0.09]]

# Building the family Bayesian model
# =============================================

familyBN = BayesianModel(edges)

# add CPDs
state_names = dict([(id, ['AA', 'aA', 'aa']) for id in familyBN.nodes()])
for c in range(1, NB_CHILDREN + 1):
    familyBN.add_cpds(TabularCPD("child" + str(c), variable_card=3, values=copy.deepcopy( inheritance_values), evidence=['target', 'spouse'], evidence_card=[3, 3], state_names=copy.deepcopy(state_names)))
familyBN.add_cpds(TabularCPD('spouse', variable_card=3, values=copy.deepcopy(apriori_values), state_names=copy.deepcopy(state_names)))
familyBN.add_cpds(TabularCPD('target', variable_card=3, values=copy.deepcopy(apriori_values), state_names=copy.deepcopy(state_names)))

# check the CPDs
print("\n\ncheck the CPDs:")
for cpd in familyBN.get_cpds():
    print(cpd)


# Doing inferrence with BeliefPropagation
# =============================================

family_inference_BP = BeliefPropagation(familyBN)
family_inference_BP.calibrate()

distrib_target_knowing_evidence_BP= family_inference_BP.query(["target"],evidence)["target"]
print("\n\nBELIEF PROPAGATION: Probability distribution of target with evidence {}:\n".format(evidence))
print(distrib_target_knowing_evidence_BP)
```

**Comment by dddpt** [comment] 2019-01-28 08:20
Hello ankurankan, I've seen you've been adding labels to the issue. Just to know (no pressure, I understand it's basically volunteering ;-) ), is anyone working on the bug?

Thanks!

**Comment by ankurankan** [comment] 2019-01-29 11:35
@tartakower No, I don't think anyone is working on this at the moment.

**Comment by gstephy** [comment] 2020-02-10 12:15
@here, This is a nasty one for me. I have a lot of nodes with children having the same CPD. Looks like this's been there for a while now, is there a known workaround?

**Comment by dddpt** [comment] 2020-02-11 12:28
Hello @gstephy!

In our case we sadly had to find another solution for inference. What we did is that we build our Bayesian Network with pgmpy and then transfer it to a [Netica](https://www.norsys.com/netica_api.html) representation for inference (with C homecooked bindings): far from optimal. The upshot is that we gained an x80 speed boost.

Another option that seems more up to date that we found after our Netica implementation (and hence didn't test) is [Smile](https://www.bayesfusion.com/smile/) from BayesFusion which is free for academic use.

Hope it helps ;-)

**Comment by gstephy** [comment] 2020-02-11 12:50
Thanks @dddpt !  Nice solution, I'll try it if I get into issues with the below workaround.

I my case, on a graph with couple hundred nodes, tiny jittering of probabilities on nodes, under each parent having children with the exact same CPDs, by say 0.001, gave me very close results. And of course I had to add few more rigorous tests to make sure the overall model stayed intact.

Hopefully this gets fixed soon and I can remove the ugly workaround. :-)

**Comment by ankurankan** [comment] 2020-02-11 18:06
@dddpt @gstephy Sorry for so much delay on this. I tried running @dddpt 's code and it has been fixed now and I am able to get the same results as the reported Matlab one. Here's the code with some minor changes because of changes in API:
```python
In [47]: from pgmpy.models import BayesianModel                                                                                                                                                                                                
    ...: from pgmpy.inference.ExactInference import VariableElimination, BeliefPropagation                                                                                                                                                     
    ...: from pgmpy.factors.discrete import TabularCPD                                                                                                                                                                                         
    ...: import copy                                                                                                                                                                                                                           
    ...:                                                                                                                                                                                                                                       
    ...:                                                                                                                                                                                                                                       
    ...:                                                                                                                                                                                                                                       
    ...: # Family parameters                                                                                                                                                                                                                   
    ...: # =============================================                                                                                                                                                                                       
    ...:                                                                                                                                                                                                                                       
    ...: for i in range(1, 6):                                                                                                                                                                                                                 
    ...:     NB_CHILDREN = i                                                                                                                                                                                                                   
    ...:     edges = [(sp, "child" + str(c)) for c in range(1, NB_CHILDREN + 1) for sp in ["target", "spouse"]]                                                                                                                                
    ...:     evidence = {"child" + str(c): 'AA' for c in range(1, NB_CHILDREN + 1)}                                                                                                                                                            
    ...:     evidence["spouse"] = 'AA'                                                                                                                                                                                                         
    ...:                                                                                                                                                                                                                                       
    ...:     # Allele distributions & Mendelian inheritance                                                                                                                                                                                    
    ...:     # =============================================                                                                                                                                                                                   
    ...:     inheritance_values = [                                                                                                                                                                                                            
    ...:         [1, 0.5, 0, 0.5, 0.25, 0, 0, 0, 0],                                                                                                                                                                                           
    ...:         [0, 0.5, 1, 0.5, 0.5, 0.5, 1, 0.5, 0],                                                                                                                                                                                        
    ...:         [0, 0, 0, 0, 0.25, 0.5, 0, 0.5, 1]                                                                                                                                                                                            
    ...:     ]                                                                                                                                                                                                                                 
    ...:     apriori_values = [[0.49],[0.42],[0.09]]                                                                                                                                                                                           
    ...:                                                                                                                                                                                                                                       
    ...:     # Building the family Bayesian model                                                                                                                                                                                              
    ...:     # =============================================                                                                                                                                                                                   
    ...:                                                                                                                                                                                                                                       
    ...:     familyBN = BayesianModel(edges)                                                                                                                                                                                                   
    ...:                                                                                                                                                                                                                                       
    ...:     # add CPDs                                                                                                                                                                                                                        
    ...:     state_names = dict([(id, ['AA', 'aA', 'aa']) for id in familyBN.nodes()])                                                                                                                                                         
    ...:     for c in range(1, NB_CHILDREN + 1):                                                                                                                                                                                               
    ...:         familyBN.add_cpds(TabularCPD("child" + str(c), variable_card=3, values=copy.deepcopy( inheritance_values), evidence=['target', 'spouse'], evidence_card=[3, 3], state_names=copy.deepcopy(state_names)))                      
    ...:     familyBN.add_cpds(TabularCPD('spouse', variable_card=3, values=copy.deepcopy(apriori_values), state_names=copy.deepcopy(state_names)))                                                                                            
    ...:     familyBN.add_cpds(TabularCPD('target', variable_card=3, values=copy.deepcopy(apriori_values), state_names=copy.deepcopy(state_names)))                                                                                            
    ...:                                                                                                                                                                                                                                       
    ...:     # Doing inferrence with BeliefPropagation                                                                                                                                                                                         
    ...:     # ============================================= 
    ...:  
    ...:     family_inference_BP = BeliefPropagation(familyBN) 
    ...:     family_inference_BP.calibrate() 
    ...:     print(family_inference_BP.query(['target'], evidence).normalize(inplace=False)) 
```
And the output:
```
0it [00:00, ?it/s]
+------------+---------------+
| target     |   phi(target) |
+============+===============+
| target(AA) |        0.7000 |
+------------+---------------+
| target(aA) |        0.3000 |
+------------+---------------+
| target(aa) |        0.0000 |
+------------+---------------+
0it [00:00, ?it/s]
+------------+---------------+
| target     |   phi(target) |
+============+===============+
| target(AA) |        0.8235 |
+------------+---------------+
| target(aA) |        0.1765 |
+------------+---------------+
| target(aa) |        0.0000 |
+------------+---------------+
0it [00:00, ?it/s]
+------------+---------------+
| target     |   phi(target) |
+============+===============+
| target(AA) |        0.9032 |
+------------+---------------+
| target(aA) |        0.0968 |
+------------+---------------+
| target(aa) |        0.0000 |
+------------+---------------+
0it [00:00, ?it/s]
+------------+---------------+
| target     |   phi(target) |
+============+===============+
| target(AA) |        0.9492 |
+------------+---------------+
| target(aA) |        0.0508 |
+------------+---------------+
| target(aa) |        0.0000 |
+------------+---------------+
0it [00:00, ?it/s]
+------------+---------------+
| target     |   phi(target) |
+============+===============+
| target(AA) |        0.9739 |
+------------+---------------+
| target(aA) |        0.0261 |
+------------+---------------+
| target(aa) |        0.0000 |
+------------+---------------+
```
I am not absolutely sure whether this was a problem in junction trees or inference because we have done some fixes in both.

@gstephy Would it be possible to share your code, so that I can reproduce your issue?

**Comment by dddpt** [comment] 2020-02-11 18:08
@ankurankan great! Good to now it's fixed ;-)

**Comment by gstephy** [comment] 2020-02-11 18:42
Here you go.. I'm using 0.1.9 and python 3.5.2
```
import itertools

from pgmpy.factors.discrete import TabularCPD
from pgmpy.inference import BeliefPropagation
from pgmpy.models import BayesianModel

model = BayesianModel()

# Nodes
parents = ['parent']
children = ['child_{}'.format(i) for i in range(10)]

# Add nodes and edges
model.add_nodes_from(parents + children)
model.add_edges_from(itertools.product(parents, children))

# Add cpds
model.add_cpds(TabularCPD(parents[0], 2,
                          [[0.5], [0.5]]))
for c in children:
    model.add_cpds(TabularCPD(c, 2, [[0.9, 0.1],
                                     [0.1, 0.9]],
                              evidence=parents,
                              evidence_card=[2]))

# Infer
inf = BeliefPropagation(model)
inf.calibrate()
evidence = {}

for c in children[:4]:
    print("Evidence:{}".format(evidence))
    print(inf.query(['parent'], evidence).normalize(inplace=False))
    evidence.update({c:1})
```
Expected:
---------
(0.5,0.5)
(0.1,0.9)
(0.0122,0.9878)
(0.0014,0.9986)
![image](https://user-images.githubusercontent.com/44619872/74268035-2a524080-4cd5-11ea-85cf-3e2988ca9fe0.png)

Actual/Output:
--------
```
Evidence:{}
Eliminating: child_0: 100%|██████████| 10/10 [00:00<00:00, 2038.74it/s]
+-----------+---------------+
| parent    |   phi(parent) |
+===========+===============+
| parent(0) |        0.5000 |
+-----------+---------------+
| parent(1) |        0.5000 |
+-----------+---------------+
Evidence:{'child_0': 1}
Eliminating: child_1: 100%|██████████| 9/9 [00:00<00:00, 2240.02it/s]
+-----------+---------------+
| parent    |   phi(parent) |
+===========+===============+
| parent(0) |        0.1000 |
+-----------+---------------+
| parent(1) |        0.9000 |
+-----------+---------------+
Evidence:{'child_1': 1, 'child_0': 1}
Eliminating: child_8: 100%|██████████| 8/8 [00:00<00:00, 2436.07it/s]
+-----------+---------------+
| parent    |   phi(parent) |
+===========+===============+
| parent(0) |        0.1000 |
+-----------+---------------+
| parent(1) |        0.9000 |
+-----------+---------------+
Evidence:{'child_2': 1, 'child_1': 1, 'child_0': 1}
Eliminating: child_8: 100%|██████████| 7/7 [00:00<00:00, 2309.46it/s]
+-----------+---------------+
| parent    |   phi(parent) |
+===========+===============+
| parent(0) |        0.1000 |
+-----------+---------------+
| parent(1) |        0.9000 |
+-----------+---------------+
```

**Closed as completed** 2020-06-12 15:41 UTC
