### ISSUE TITLE
Bug in BayesianModel.predict

### ISSUE THREAD

**Issue by yashu-seth** [pgmpy/pgmpy#698] opened 2016-06-13 18:52 UTC
``` python
wd = "C:/work/R/"
import os
os.chdir(wd)

import pandas
import numpy as np

##data_link - "https://www.kaggle.com/c/titanic/download/train.csv"
data = pandas.read_csv("kaggle.csv")
data2 = data[["Survived", "Sex", "Pclass"]]

intrain = np.random.rand(len(data2)) < 0.8

dtrain = data2[intrain]
dtest = data2[~intrain]

##print(len(dtrain), len(dtest))

from pgmpy.models import BayesianModel
titanic = BayesianModel()
titanic.add_edges_from([("Sex", "Survived"), ("Pclass", "Survived")])
titanic.fit(dtrain)
for cpd in titanic.get_cpds():
    print(cpd)

╒═════════════╤══════════╕
│ Sex(female) │ 0.340909 │
├─────────────┼──────────┤
│ Sex(male)   │ 0.659091 │
╘═════════════╧══════════╛
╒═════════════╤══════════════════════╤════════════════════╤═════════════════════╤═════════════════════╤═════════════════════╤═════════════════════╕
│ Pclass      │ Pclass(1)            │ Pclass(1)          │ Pclass(2)           │ Pclass(2)           │ Pclass(3)           │ Pclass(3)           │
├─────────────┼──────────────────────┼────────────────────┼─────────────────────┼─────────────────────┼─────────────────────┼─────────────────────┤
│ Sex         │ Sex(female)          │ Sex(male)          │ Sex(female)         │ Sex(male)           │ Sex(female)         │ Sex(male)           │
├─────────────┼──────────────────────┼────────────────────┼─────────────────────┼─────────────────────┼─────────────────────┼─────────────────────┤
│ Survived(0) │ 0.029411764705882353 │ 0.6372549019607843 │ 0.08333333333333333 │ 0.8452380952380952  │ 0.49107142857142855 │ 0.8597122302158273  │
├─────────────┼──────────────────────┼────────────────────┼─────────────────────┼─────────────────────┼─────────────────────┼─────────────────────┤
│ Survived(1) │ 0.9705882352941176   │ 0.3627450980392157 │ 0.9166666666666666  │ 0.15476190476190477 │ 0.5089285714285714  │ 0.14028776978417265 │
╘═════════════╧══════════════════════╧════════════════════╧═════════════════════╧═════════════════════╧═════════════════════╧═════════════════════╛
╒═══════════╤══════════╕
│ Pclass(1) │ 0.241477 │
├───────────┼──────────┤
│ Pclass(2) │ 0.204545 │
├───────────┼──────────┤
│ Pclass(3) │ 0.553977 │
╘═══════════╧══════════╛

titanic.predict(dtest[["Sex", "Pclass"]])

Traceback (most recent call last):
  File "C:/Python34/pgmpy_titanic.py", line 25, in <module>
    titanic.predict(dtest[["Sex", "Pclass"]])
  File "c:\work\pgmpy\pgmpy\models\BayesianModel.py", line 633, in predict
    states_dict = model_inference.map_query(variables=missing_variables, evidence=data_point.to_dict())
  File "c:\work\pgmpy\pgmpy\utils\state_name.py", line 167, in wrapper
    return f(*args, **kwargs)
  File "c:\work\pgmpy\pgmpy\inference\ExactInference.py", line 195, in map_query
    elimination_order=elimination_order)
  File "c:\work\pgmpy\pgmpy\utils\state_name.py", line 167, in wrapper
    return f(*args, **kwargs)
  File "c:\work\pgmpy\pgmpy\inference\ExactInference.py", line 50, in _variable_elimination
    factor_reduced = factor.reduce([(evidence_var, evidence[evidence_var])], inplace=False)
  File "c:\work\pgmpy\pgmpy\utils\state_name.py", line 167, in wrapper
    return f(*args, **kwargs)
  File "c:\work\pgmpy\pgmpy\factors\Factor.py", line 421, in reduce
    raise TypeError("values: must contain tuples or array-like elements of the form "
TypeError: values: must contain tuples or array-like elements of the form (hashable object, type int)
```

**Comment by yashu-seth** [comment] 2016-06-13 18:55
I hope I am using the predict method the in the correct fashion.

**Comment by yashu-seth** [comment] 2016-06-13 19:42
I ran the same code again and got a different error.

``` python
titanic.predict(dtest[["Sex", "Pclass"]])
Traceback (most recent call last):
  File "C:/Python34/pgmpy_titanic.py", line 26, in <module>
    titanic.predict(dtest[["Sex", "Pclass"]])
  File "c:\work\pgmpy\pgmpy\models\BayesianModel.py", line 633, in predict
    states_dict = model_inference.map_query(variables=missing_variables, evidence=data_point.to_dict())
  File "c:\work\pgmpy\pgmpy\utils\state_name.py", line 167, in wrapper
    return f(*args, **kwargs)
  File "c:\work\pgmpy\pgmpy\inference\ExactInference.py", line 195, in map_query
    elimination_order=elimination_order)
  File "c:\work\pgmpy\pgmpy\utils\state_name.py", line 167, in wrapper
    return f(*args, **kwargs)
  File "c:\work\pgmpy\pgmpy\inference\ExactInference.py", line 50, in _variable_elimination
    factor_reduced = factor.reduce([(evidence_var, evidence[evidence_var])], inplace=False)
  File "c:\work\pgmpy\pgmpy\utils\state_name.py", line 167, in wrapper
    return f(*args, **kwargs)
  File "c:\work\pgmpy\pgmpy\factors\Factor.py", line 438, in reduce
    phi.values = phi.values[tuple(slice_)]
IndexError: index 3 is out of bounds for axis 0 with size 3

```

**Comment by chrisittner** [comment] 2016-06-16 15:19
It is a state name issue. I also get the first error. If I replace the line 

``` python
data2 = data[["Survived", "Sex", "Pclass"]]
```

with 

``` python
data2 = data[["Survived", "Sex", "Pclass"]].replace(["female", "male"], [0, 1])
```

to get rid of non-int values, then I get the second error. If I again replace that line with

``` python
data2 = data[["Survived", "Sex", "Pclass"]].replace(["female", "male"], [0, 1]).replace({"Pclass": {3: 0}})
```

to make the "Pclass"-values `0`,`1`,`2` rather than `1`,`2`,`3`,  it appears to work.

The code tries to use the "external" statenames (that are currently managed via the decorators) rather than the "internal" ones as an index for `Factor.values` in `reduce()`.

I saw that `Factor.reduce`, `VariableElimination._variable_elimination`, `VariableElimination.map_query` (the methods between `predict()` and the error) all have a `StateNameDecorator`. But the state name wrapper functions all return in [this](https://github.com/pgmpy/pgmpy/blob/dev/pgmpy/utils/state_name.py#L167) line already, because they can't find the state names (you can put a `print`-statement before that line to see it).

**Comment by chrisittner** [comment] 2016-06-16 15:43
More generally: I think the `state_name`-support is important for handling actual data, it is not just a convenience feature. So at first sight, the situation with "internal" names for variable states and "external" names that are added by decorators doesn't seem ideal, because it currently makes it difficult to understand which names are used when (at least for me).

**Comment by chrisittner** [comment] 2016-06-16 15:55
Why is it necessary to wrapper methods in the `/inference/`-folder with `@StateNameDecorator`? I thought the decorators only serve to transparently change the "row and column names" of `values` of `Factor`s, so can't it be such that they only appear in `/factors/`?

**Comment by yashu-seth** [comment] 2016-06-16 18:08
@chrisittner I think I found the problem, in the predict method - 
[This](https://github.com/pgmpy/pgmpy/blob/dev/pgmpy/models/BayesianModel.py#L646) line ensures that evidence dict is passed with the actual state names ({'Sex': 'male', 'Pclass': 3}) but [here](https://github.com/pgmpy/pgmpy/blob/dev/pgmpy/models/BayesianModel.py#L644) there is no  state_names dict passed during the initializtion of the inference instance. Hence, the problem. This can be fixed by adding in line 644  - 

``` python
model_inference = VariableElimination(self, state_names=self.get_cpds()[0].state_names)
```

But there should be a better way to pass the state dicts.

**Comment by yashu-seth** [comment] 2016-06-16 18:12
@chrisittner There are a lot of places where the internal architecture has been used for state names. I think we cannot get rid of this because forcing the users to provide a state names dict every time would not be very good. Do you have an idea of some other way to handle this?

**Comment by yashu-seth** [comment] 2016-06-16 18:14
@chrisittner I did not understand [your last comment](https://github.com/pgmpy/pgmpy/issues/698#issuecomment-226529613). Can you please elaborate it?

**Comment by yashu-seth** [comment] 2016-06-16 18:48
The way the state names feature has been implemented is that we need to pass a state names dict as input parameter while initializing an instance of either a `Factor`, `TabularCPD` or `Inference` class. If a state names dict is passed, all the methods can work on both internal state names or the custom state names. So we can pass the parameters either way for methods like `reduce`, `map_query` etc. The only case when this will not (and should not) work is when there is no state names dict provided during initialization but we are passing arguments with custom state names that are not consistent with the internal architecture of the state names (as the case above).

**Comment by khalibartan** [comment] 2017-08-03 15:41
@yashu-seth @ankurankan I'm still getting following even after converting dataframe to type string.
```
In [61]: ot = model.predict(dt)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-61-b1a1a9d01335> in <module>()
----> 1 ot = model.predict(dt)

/home/utgup/anaconda3/lib/python3.5/site-packages/pgmpy-0.1.3-py3.5.egg/pgmpy/models/BayesianModel.py in predict(self, data)
    739         model_inference = VariableElimination(self)
    740         for index, data_point in data.iterrows():
--> 741             states_dict = model_inference.map_query(variables=missing_variables, evidence=data_point.to_dict())
    742             for k, v in states_dict.items():
    743                 pred_values[k].append(v)

/home/utgup/anaconda3/lib/python3.5/site-packages/pgmpy-0.1.3-py3.5.egg/pgmpy/utils/state_name.py in __call__(self, f, instance, args, kwargs)
    165 
    166         if not method_self.state_names:
--> 167             return f(*args, **kwargs)
    168         else:
    169             self.state_names = method_self.state_names

/home/utgup/anaconda3/lib/python3.5/site-packages/pgmpy-0.1.3-py3.5.egg/pgmpy/inference/ExactInference.py in map_query(self, variables, evidence, elimination_order)
    199         final_distribution = self._variable_elimination(elimination_variables, 'maximize',
    200                                                         evidence=evidence,
--> 201                                                         elimination_order=elimination_order)
    202         # To handle the case when no argument is passed then
    203         # _variable_elimination returns a dict.

/home/utgup/anaconda3/lib/python3.5/site-packages/pgmpy-0.1.3-py3.5.egg/pgmpy/utils/state_name.py in __call__(self, f, instance, args, kwargs)
    165 
    166         if not method_self.state_names:
--> 167             return f(*args, **kwargs)
    168         else:
    169             self.state_names = method_self.state_names

/home/utgup/anaconda3/lib/python3.5/site-packages/pgmpy-0.1.3-py3.5.egg/pgmpy/inference/ExactInference.py in _variable_elimination(self, variables, operation, evidence, elimination_order)
     54             for evidence_var in evidence:
     55                 for factor in working_factors[evidence_var]:
---> 56                     factor_reduced = factor.reduce([(evidence_var, evidence[evidence_var])], inplace=False)
     57                     for var in factor_reduced.scope():
     58                         working_factors[var].remove(factor)

/home/utgup/anaconda3/lib/python3.5/site-packages/pgmpy-0.1.3-py3.5.egg/pgmpy/utils/state_name.py in __call__(self, f, instance, args, kwargs)
    165 
    166         if not method_self.state_names:
--> 167             return f(*args, **kwargs)
    168         else:
    169             self.state_names = method_self.state_names

/home/utgup/anaconda3/lib/python3.5/site-packages/pgmpy-0.1.3-py3.5.egg/pgmpy/factors/discrete/DiscreteFactor.py in reduce(self, values, inplace)
    417         if (any(isinstance(value, six.string_types) for value in values) or
    418                 not all(isinstance(state, (int, np.integer)) for var, state in values)):
--> 419             raise TypeError("values: must contain tuples or array-like elements of the form "
    420                             "(hashable object, type int)")
    421 

TypeError: values: must contain tuples or array-like elements of the form (hashable object, type int)
```

**Comment by lohani2280** [comment] 2017-08-25 19:21
@ankurankan  This issue has been solved in PR https://github.com/pgmpy/pgmpy/pull/800 . I guess we should close this issue now.

**Comment by atena2019** [comment] 2017-10-24 18:42
I have this issue as well. the exception 
IndexError: index 3 is out of bounds for axis 0 with size 3
has been  raised. I installed the current version of pgmpy. how can i fix it? should i choose a special name for my columns?
Some of my column data is between 0 and 9. some other between 0 and 5 and etc.

**Comment by ankurankan** [comment] 2017-10-25 14:24
@atena2019 Can you please share your code for us to reproduce the issue ? Yes, the column names need  to be exactly same as the variable names that they are representing.

**Comment by atena2019** [comment] 2017-10-25 20:29
Thanks dear @ankurankan. I shared my code in issue #916

**Comment by atena2019** [comment] 2017-10-25 21:18
I found that when i test the predict method for data that have non- binary columns, if the test data contain the maximum value of the data, the exception is raised. for example for a column that can have 4 values( i.e. 0,1,2,3), when the test data has 3 in the features values, the exception is raised. I think the decorators should change.

**Comment by atena2019** [comment] 2017-10-27 18:56
dear @ankurankan  did you check the issue? am i right?

**Comment by atena2019** [comment] 2017-11-01 19:32
I found the answer. the problem was because of my data, not pgmpy. Thanks for opening the issue. it can be closed.  
Best regards

**Closed as completed** 2017-11-04 23:29 UTC
Labels: Bug

**Comment by sharonml** [comment] 2022-07-18 20:38
hi @atena2019! I know it's been a while, but do you remember the solution you found?

You may still need to make a prediction for a test data point that contains the maximum value right? The model should not throw an error in that case... I'm running into this same error as well so would be great to know what you found.

**Comment by ankurankan** [comment] 2022-08-15 18:31
@sharonml Sorry for the late reply. If you are getting a similar error, it's probably because the test dataset has states for variables that were not present in the training dataset.
