### ISSUE TITLE
Bugs in MaximumLikelihoodEstimator.get_parameters()

### ISSUE THREAD

**Issue by yashu-seth** [pgmpy/pgmpy#579] opened 2016-01-15 17:08 UTC
The `MaximumLikelihoodEstimator.get_parameters()` is not properly working. Work needs to be done to make it bug free.

**Comment by yashu-seth** [comment] 2016-01-15 17:11
@ankurankan You once suggested that we should move to a complete numpy implementation. Should input as pandas dataframe objects be allowed or that should also be done using numpy arrays?

**Comment by khalibartan** [comment] 2016-01-15 17:25
@yashu-seth Can you elaborate the bug in it.

**Comment by yashu-seth** [comment] 2016-01-15 17:36
```python
>>> data = pd.DataFrame(columns=('a', 'b', 'c', 'd'))
>>> for i in range(250):
           data3.loc[i] = [0,1,0,0]
>>> for i in range(250,500):
           data3.loc[i] = [1,1,1,0]
>>> for i in range(500,1000):
           data3.loc[i] = [1,0,0,0]
>>> data3.ix[:,'a'].value_counts()
1    750
0    250
dtype: int64
>>> data3.ix[:,'c'].value_counts()
0    750
1    250
dtype: int64
```
When we convert these to numpy arrays both give the same numpy array - ```array([[750], [250]], dtype=int64)```. It should not happen.

**Comment by yashu-seth** [comment] 2016-01-15 17:42
@khalibartan Working with pandas dataframes at times does not give sorted results which gives incorrect values for variables in CPD. Also there is issue #573 .

**Comment by yashu-seth** [comment] 2016-01-15 17:43
@khalibartan I am planning to use a completely numpy based soulution.

**Comment by yashu-seth** [comment] 2016-01-16 11:59
@ankurankan What do you feel about this?

**Comment by ankurankan** [comment] 2016-01-18 05:53
@yashu-seth Can you elaborate on the bugs that you found ?

**Comment by yashu-seth** [comment] 2016-01-18 10:04
@ankurankan 

``` python
>>> model = BayesianModel([('A', 'B'), ('C', 'B'), ('C', 'D'), ('B', 'E')])
>>> values = pd.DataFrame(np.random.randint(low=0, high=2, size=(1000, 5)),
                              columns=['A', 'B', 'C', 'D', 'E'])
>>> fit_data = values[:800]
>>> model.fit(fit_data)

Traceback (most recent call last):
  File "<pyshell#12>", line 1, in <module>
    model.fit(fit_data)
  File "c:\work\pgmpy\pgmpy\models\BayesianModel.py", line 557, in fit
    cpds_list = estimator.get_parameters()
  File "c:\work\pgmpy\pgmpy\estimators\MLE.py", line 66, in get_parameters
    state_counts.values[:, np.newaxis])
  File "c:\work\pgmpy\pgmpy\factors\CPD.py", line 105, in __init__
    raise TypeError("Event cardinality must be an integer")
TypeError: Event cardinality must be an integer
```

**Comment by ankurankan** [comment] 2016-01-18 10:22
@yashu-seth This works for me both on python 2 and 3.

**Comment by yashu-seth** [comment] 2016-01-18 10:30
@ankurankan
For line 63, in MLE.py,

``` python
>>> data = pd.DataFrame(columns=('a', 'b', 'c', 'd'))
>>> for i in range(250):
           data.loc[i] = [0,1,0,0]
>>> for i in range(250,500):
           data.loc[i] = [1,1,1,0]
>>> for i in range(500,1000):
           data.loc[i] = [1,0,0,1]
>>> model = BayesianModel([('b','a'), ('d','a'), ('b','c'), ('d','c')])
>>> data.groupby(['b','c','d']).size().unstack(['b','d']).fillna(0)
b    0    1
d    1    0
c          
0  500  250
1    0  250
>>> data.groupby(['b','a','d']).size().unstack(['b','d']).fillna(0)
b    0    1
d    1    0
a          
0  500    0
1    0  500
```

These should give 8 values and not 4 because according to the data cardinality of 'b' and 'd' both is 2. Hence it should not neglect the case when 'b' and 'd' both are 0 or 1 and should have a 0 in the cpd for such cases.

**Comment by yashu-seth** [comment] 2016-01-18 10:32
@ankurankan okay let me have a look at the first issue once again. its strange that it is throwing an error for me.

**Comment by yashu-seth** [comment] 2016-01-18 22:50
@khalibartan Can you please try and reproduce the first bug that I mentioned. I am still getting it.

**Comment by yashu-seth** [comment] 2016-01-18 23:11
@ankurankan I just checked the cardinality of the event is type long. That is why it is throwing error for me. Can you please look at it once again.

**Comment by yashu-seth** [comment] 2016-01-18 23:14
@ankurankan Even after fixing it I get the following error - 

``` python
Traceback (most recent call last):
  File "C:/work/temp/yuiop.py", line 9, in <module>
    model.fit(fit_data)
  File "c:\work\pgmpy\pgmpy\models\BayesianModel.py", line 557, in fit
    cpds_list = estimator.get_parameters()
  File "c:\work\pgmpy\pgmpy\estimators\MLE.py", line 67, in get_parameters
    state_counts.values[:, np.newaxis])
  File "c:\work\pgmpy\pgmpy\factors\CPD.py", line 140, in __init__
    super(TabularCPD, self).__init__(variables, cardinality, values.flatten('C'))
  File "c:\work\pgmpy\pgmpy\factors\Factor.py", line 100, in __init__
    raise TypeError("Values: Expected type int or type float, got ", values.dtype)
TypeError: ('Values: Expected type int or type float, got ', dtype('int64'))
```

**Comment by khalibartan** [comment] 2016-01-19 02:48
@yashu-seth I'm not getting any errors in my system. Haven't checked for python2

**Comment by ankurankan** [comment] 2016-01-19 04:40
@yashu-seth Can you double check that you have the correct versions of dependencies installed and you have the latest dev branch ?

**Comment by yashu-seth** [comment] 2016-01-19 06:41
@khalibartan @ankurankan okay let me check. something must be wrong with the depedndencies installed.

**Comment by yashu-seth** [comment] 2016-01-19 06:42
@ankurankan Please have a look at the second bug that I mentioned.

**Comment by yashu-seth** [comment] 2016-01-19 06:43
@khalibartan 

``` python
TypeError: ('Values: Expected type int or type float, got ', dtype('int64'))
```

Did you get this error or there were no errors at all?

**Comment by khalibartan** [comment] 2016-01-19 06:59
@yashu-seth No I didn't get any errors for code mentioned [here](https://github.com/pgmpy/pgmpy/issues/579#issuecomment-172484290) in both versions of python .

**Comment by yashu-seth** [comment] 2016-01-19 07:14
@khalibartan thanks. I'll check the dependencies.

**Comment by yashu-seth** [comment] 2016-01-19 07:15
@khalibartan What do you feel about the second bug that I had mentioned?

**Comment by khalibartan** [comment] 2016-01-19 07:17
@yashu-seth I couldn't reproduce, which bug are you talking about ? (Give me the link of comment or code to reproduce it).

**Comment by yashu-seth** [comment] 2016-01-19 07:31
@khalibartan 

``` python
>>> data = pd.DataFrame(columns=('a', 'b', 'c', 'd'))
>>> for i in range(250):
           data.loc[i] = [0,1,0,0]
>>> for i in range(250,500):
           data.loc[i] = [1,1,1,0]
>>> for i in range(500,1000):
           data.loc[i] = [1,0,0,1]
>>> model = BayesianModel([('b','a'), ('d','a'), ('b','c'), ('d','c')])
>>> data.groupby(['b','c','d']).size().unstack(['b','d']).fillna(0)
b    0    1
d    1    0
c          
0  500  250
1    0  250
>>> data.groupby(['b','a','d']).size().unstack(['b','d']).fillna(0)
b    0    1
d    1    0
a          
0  500    0
1    0  500
```

These should give 8 values and not 4 because according to the data cardinality of 'b' and 'd' both is 2. Hence it should not neglect the case when 'b' and 'd' both are 0 or 1 and should have a 0 in the cpd for such cases.

**Comment by khalibartan** [comment] 2016-01-19 07:46
@yashu-seth I'm not getting the same output as yours.

```
In [1]: from pgmpy.models import BayesianModel

In [2]: import pandas as pd

In [3]: import numpy as np

In [4]: %paste
>>> data = pd.DataFrame(columns=('a', 'b', 'c', 'd'))
>>> for i in range(250):
           data.loc[i] = [0,1,0,0]
>>> for i in range(250,500):
           data.loc[i] = [1,1,1,0]
>>> for i in range(500,1000):
           data.loc[i] = [1,0,0,1]
>>> model = BayesianModel([('b','a'), ('d','a'), ('b','c'), ('d','c')])
>>> data.groupby(['b','c','d']).size().unstack(['b','d']).fillna(0)

## -- End pasted text --
Out[4]: 
b    0    1
d    1    0
c          
0  500  250
1    0  250

In [5]: data.groupby(['b','a','d']).size().unstack(['b','d']).fillna(0)
Out[5]: 
b    0    1
d    1    0
a          
0    0  250
1  500  250

```

**Comment by yashu-seth** [comment] 2016-01-19 08:18
@khalibartan okay but anyway both outputs are wrong. isn't it? As far as the different outputs are concerned let me check.

**Comment by yashu-seth** [comment] 2016-01-19 18:31
@khalibartan I copied the wrong output that is why it was giving different outputs. But anyway my point is that is should give 8 values and not 4. It should give - 

``` python
b      0      0        1        1
d      0      1        0        1
a          
0      0      0        250      0
1      0      500      250      0
```

**Comment by khalibartan** [comment] 2016-01-20 02:49
@yashu-seth Why it is doing so? means why only 4 outputs are being shown instead of 8

**Comment by yashu-seth** [comment] 2016-01-20 11:53
@khalibartan Because this is how things have been implemented and it is incorrect. 
@ankurankan What should we do about it?

**Comment by chrisittner** [comment] 2016-03-13 17:13
What is the status here? I agree with @yashu-seth that this `get_parameters` should be fixed. The second bug isn't hard to fix, it just requires a decision. 

I'll try to summarize the issues again. I think @yashu-seth pointed to two independent bugs with `get_parameters()`:
- Some exception that wasn't easy to reproduce. I think this is the windows issue #602 with pandas, and it is addressed in #604, so it might be solved already (can't check, no windows).
- A bug about the cardinality of the CPDs. This is the very same issue as #352 and #573. I'll describe it below:

**Problem:**
An exception occurs in `get_parameters()` if the data set does not include at least one sample for _every_ configuration that the parents of any variable may have.
**Minimal example:**

``` python
>>> from pandas import DataFrame
>>> from pgmpy.models import BayesianModel
>>> from pgmpy.estimators import MaximumLikelihoodEstimator
>>> m = BayesianModel([('A','C'), ('B','C')])
>>> d = DataFrame(data={'A':[0,0,1], 'B':[0,1,0], 'C':[1,1,0]})
>>> d
   A  B  C
0  0  0  1
1  0  1  1
2  1  0  0
>>> cpds = MaximumLikelihoodEstimator(m,d).get_parameters()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lodrik/tmppgmpy/pgmpy/pgmpy/estimators/MLE.py", line 75, in get_parameters
    evidence_card=parent_card.astype('int'))
  File "/home/lodrik/tmppgmpy/pgmpy/pgmpy/factors/CPD.py", line 141, in __init__
    super(TabularCPD, self).__init__(variables, cardinality, values.flatten('C'))
  File "/home/lodrik/tmppgmpy/pgmpy/pgmpy/factors/Factor.py", line 106, in __init__
    raise ValueError("Values array must be of size: {size}".format(size=np.product(cardinality)))
ValueError: Values array must be of size: 8
```

The data set contains a data point with `A=0`,`B=0`, one for `A=0`,`B=1` and one for `A=1`,`B=0`, but no data where `A=1` and `B=1`. Thus, for variable `C`, there exists a parent configuration for which we get no information about `C`'s state from the data. With an additional data sample, the error goes away:

``` python
>>> from pandas import DataFrame
>>> from pgmpy.models import BayesianModel
>>> from pgmpy.estimators import MaximumLikelihoodEstimator
>>> m = BayesianModel([('A','C'), ('B','C')])
>>> d = DataFrame(data={'A':[0,0,1,1], 'B':[0,1,0,1], 'C':[1,1,0,0]})
>>> d
   A  B  C
0  0  0  1
1  0  1  1
2  1  0  0
3  1  1  0
>>> cpds = MaximumLikelihoodEstimator(m,d).get_parameters()
>>> print(cpds[0])
╒═════╤═════╕
│ A_0 │ 0.5 │
├─────┼─────┤
│ A_1 │ 0.5 │
╘═════╧═════╛
>>> print(cpds[2])
╒═════╤═════╕
│ B_0 │ 0.5 │
├─────┼─────┤
│ B_1 │ 0.5 │
╘═════╧═════╛
>>> print(cpds[1])
╒═════╤═════╤═════╤═════╤═════╕
│ A   │ A_0 │ A_0 │ A_1 │ A_1 │
├─────┼─────┼─────┼─────┼─────┤
│ B   │ B_0 │ B_1 │ B_0 │ B_1 │
├─────┼─────┼─────┼─────┼─────┤
│ C_0 │ 1.0 │ 1.0 │ 0.0 │ 0.0 │
├─────┼─────┼─────┼─────┼─────┤
│ C_1 │ 0.0 │ 0.0 │ 1.0 │ 1.0 │
╘═════╧═════╧═════╧═════╧═════╛
```

**Solution:**
@yashu-seth [spotted](https://github.com/pgmpy/pgmpy/issues/579#issuecomment-172763485) the issue in [line 72](https://github.com/pgmpy/pgmpy/blob/dev/pgmpy/estimators/MLE.py#L72), where the resulting value table does not contain a column for every _possible_ configuration of the parents, but only for those which are _observed_ in the sample.

To fix this we just have to extend the value table to include conditional probabilities for all states the parents variables may have (# of columns should the the product of the cardinalities of the parents).

The only question is: **What conditional probabilities should a Maximum Likelihood estimator estimate if the sample size (for a particular configuration of parents) is zero?** :D  It is a bit arbitrary, but I would suggest uniform probabilities. So in the example of a binary variable `C` above, if no data was observed for the case `A=1`, `B=1`, then `P(C=0|A=1,B=1)=P(C=1|A=1,B=1)=1/2`.

So we just have to complete the value table from [line 72](https://github.com/pgmpy/pgmpy/blob/dev/pgmpy/estimators/MLE.py#L72) by adding a column for each missing parent configuration with uniform values `1/card` (where `card` is the number of states the current variable can take).

@yashu-seth @ankurankan Can I send a PR?

**Comment by yashu-seth** [comment] 2016-03-13 17:53
@chrisittner I agree the case is arbitrary. And I also think assigning uniform probabilities is the best way to deal with it.
So +1 for the PR.
I feel may be we can issue a warning for data sets missing particular configurations of parents.

**Comment by chrisittner** [comment] 2016-03-13 18:16
Thanks, good. I'll propose a fix tomorrow. I don't know how we could warn the user? (It's not worth an exception, because for nodes with several parents and higher cardinality such cases will occur regularly)

**Comment by yashu-seth** [comment] 2016-03-13 18:36
@chrisittner Yes certainly not an exception. We can issue warnings using [this](https://docs.python.org/2/library/warnings.html) in python.
I think you should go ahead with the PR and figure out if a warning is required or not later.

**Comment by chrisittner** [comment] 2016-03-14 02:29
@yashu-seth :D Ahh, that is where warnings come from. 
OK, I didn't include a warning; on second thought the behavior isn't very unexpected.

**Comment by chrisittner** [comment] 2016-03-27 21:36
This can be closed, I think. Fixed in #667.

**Closed as completed** 2016-03-28 02:59 UTC

**Comment by annesoj** [comment] 2017-03-16 15:14
Hi everyone,
I re-open this post because I did not find any answer to the problem...
@ankurankan 

I tried to use pgmpy package with a simple code I found on the internet:

`>>> import pandas as pd
>>> from pgmpy.models import BayesianModel
>>> from pgmpy.estimators import MaximumLikelihoodEstimator
>>> model = BayesianModel([('A', 'C'), ('B', 'C')])
>>> data = pd.DataFrame(data={'A': [0, 0, 1], 'B': [0, 1, 0], 'C': [1, 1, 0]})
>>> model.fit(data)`

I got the same error than @yashu-seth 

   103 
    104         if not isinstance(variable_card, int):
--> 105             raise TypeError("Event cardinality must be an integer")
    106         self.variable_card = variable_card
    107 

TypeError: Event cardinality must be an integer

I do not understand... To me, variable_card is the number of modalities of each variable. How can it be anything else than an integer? For me it is 2 for 'A', 2 for 'B' and 2 for 'C'... I only have zero and one values....

If anyone can help!!! Thank you very much!!

@yashu-seth you said "I just checked the cardinality of the event is type long. That is why it is throwing error for me. Can you please look at it once again."

How do you check the cardinality of the event???
What is the cardinality of the event? Isn't it "0" or "1"????

**Comment by dhmodi** [comment] 2017-06-27 17:15
Hi All,

I am also facing the same issue. Tried the sample code given in above comments.

```
DataTypes:
A    int32
B    int32
C    int32
D    int32
E    int32


  File "C:\Python27\lib\site-packages\pgmpy\models\BayesianModel.py", line 570, in fit
    cpds_list = estimator.get_parameters()
  File "C:\Python27\lib\site-packages\pgmpy\estimators\MLE.py", line 66, in get_parameters
    state_counts.values[:, np.newaxis])
  File "C:\Python27\lib\site-packages\pgmpy\factors\CPD.py", line 105, in __init__
    raise TypeError("Event cardinality must be an integer")
TypeError: Event cardinality must be an integer
```

Update:
I was trying with version 0.1.2 and was facing above issue.
But it is rectified in v0.1.3

Observation:
v0.1.3 is not detected by pip. Hence manual installation is required.
